# URL for the login page
orderurl=https://staging.dataverify.com/dvweb/user/taxtranscripts/ordertt.aspx?asc=4506
afterLoginUrl=https://staging.dataverify.com/dvweb/default.aspx
login.url=https://staging.dataverify.com/dvweb/user/login.aspx
searchOrderurl=https://staging.dataverify.com/dvweb/user/taxtranscripts/searchtt.aspx
detailsUrl

# W2 form credentials
username=venkiuat
password=Accionlabs@2052

# Personal details for the 4506 order form
firstName=John
lastName=Doe
ssn=123456789
dob=01/01/1980
year=2024

# Dashboard URL after successful login
dashboard.url=https://staging.dataverify.com/dvweb/user/dashboard
